class keywordData {
  static Map<String, List> countryKeywords = {
    'Afghanistan': [
      'Afghan',
      'Pashto',
      'Dari',
      'Central Asia',
      'South Asia',
      'Kabul',
      'Hindu Kush',
      'Islamic Republic of Afghanistan',
      'War-torn',
      'Taliban'
    ],
    'Åland Islands': [
      'Åland',
      'Scandinavia',
      'Nordic',
      'Autonomous Region',
      'Finnish',
      'Mariehamn',
      'Baltic Sea',
      'Swedish',
      'Demilitarized',
      'European Union'
    ],
    'Albania': [
      'Albanian',
      'Tirana',
      'Balkan',
      'Southern Europe',
      'Adriatic Sea',
      'European',
      'Muslim',
      'Illyrians',
      'Communist',
      'Enver Hoxha'
    ],
    'Algeria': [
      'Algerian',
      'Arab',
      'Berber',
      'Algiers',
      'North Africa',
      'Maghreb',
      'Sahara Desert',
      'Mediterranean',
      'Arabic',
      'Islam'
    ],
    'American Samoa': [
      'American Samoa',
      'Pacific',
      'Polynesia',
      'Pago Pago',
      'U.S. Territory',
      'Samoan',
      'Pacific Islander',
      'Tutuila',
      'Coral reefs',
      'Tropical'
    ],
    'Andorra': [
      'Andorra',
      'Pyrenees',
      'Catalan',
      'Andorran',
      'Landlocked',
      'Europe',
      'Skiing',
      'Tourism',
      'Microstate',
      'Iberian Peninsula'
    ],
    'Angola': [
      'Angolan',
      'Luanda',
      'Lusophone',
      'Southern Africa',
      'Oil-rich',
      'Bantu',
      'Civil War',
      'Portuguese',
      'Atlantic Coast',
      'Cuanza River'
    ],
    'Anguilla': [
      'Anguilla',
      'Caribbean',
      'British Overseas Territory',
      'The Valley',
      'Anguillian',
      'Turquoise waters',
      'Coral reefs',
      'Beaches',
      'Caribbean Sea',
      'British'
    ],
    'Antigua and Barbuda': [
      'Antigua and Barbuda',
      'Caribbean',
      'Saint John\'s',
      'English Harbour',
      'Tropical',
      'Island nation',
      'Tourism',
      'English',
      'Commonwealth',
      'West Indies'
    ],
    'Argentina': [
      'Argentinian',
      'Buenos Aires',
      'Spanish',
      'South America',
      'Pampas',
      'Tango',
      'Andes',
      'Patagonia',
      'Mate',
      'Latin American'
    ],
    'Armenia': [
      'Armenian',
      'Yerevan',
      'Caucasus',
      'Christian',
      'Ararat',
      'Mountains',
      'Soviet Republic',
      'Eurasia',
      'Transcaucasia',
      'Yerevan'
    ],
    'Aruba': [
      'Aruba',
      'Caribbean',
      'Oranjestad',
      'Dutch',
      'Papiamento',
      'Island',
      'Tourism',
      'Beaches',
      'Diving',
      'Kingdom of the Netherlands'
    ],
    'Ascension Island': [
      'Ascension Island',
      'Atlantic',
      'Remote',
      'British Overseas Territory',
      'Saint Helena',
      'Ascension Day',
      'Isolation',
      'Strategic',
      'Wideawake Airfield',
      'Volcanic'
    ],
    'Australia': [
      'Australian',
      'Sydney',
      'Melbourne',
      'Oceania',
      'Great Barrier Reef',
      'Aboriginal',
      'Outback',
      'Commonwealth',
      'Southern Hemisphere',
      'Aussie'
    ],
    'Austria': [
      'Austrian',
      'Vienna',
      'Alps',
      'Central Europe',
      'Habsburg',
      'Germanic',
      'Danube',
      'Music',
      'Classical',
      'European Union'
    ],
    'Azerbaijan': [
      'Azerbaijani',
      'Baku',
      'Caucasus',
      'Turkic',
      'Caspian Sea',
      'Oil-rich',
      'Soviet Republic',
      'Nagorno-Karabakh',
      'Shah Deniz',
      'Eurasia'
    ],
    'Bahamas': [
      'Bahamian',
      'Nassau',
      'Caribbean',
      'Island nation',
      'Turquoise waters',
      'Exuma Cays',
      'Pirates',
      'Commonwealth of Nations',
      'Lucayan',
      'Conch'
    ],
    'Bahrain': [
      'Bahraini',
      'Manama',
      'Arab',
      'Persian Gulf',
      'Island nation',
      'Modern',
      'Oil-rich',
      'Kingdom',
      'Pearl diving',
      'Arabic'
    ],
    'Bangladesh': [
      'Bangladeshi',
      'Dhaka',
      'Bengali',
      'South Asia',
      'Ganges Delta',
      'Bay of Bengal',
      'Dhaka',
      'Cyclones',
      'Textiles',
      'Sundarbans'
    ],
    'Barbados': [
      'Barbadian',
      'Bridgetown',
      'Caribbean',
      'English',
      'Island nation',
      'Tourism',
      'Rum',
      'Cricket',
      'Sugar cane',
      'Commonwealth'
    ],
    'Belarus': [
      'Belarusian',
      'Minsk',
      'Eastern Europe',
      'Slavic',
      'Chernobyl',
      'Soviet Republic',
      'Lukashenko',
      'Baltic Sea',
      'Russian',
      'European'
    ],
    'Belgium': [
      'Belgian',
      'Brussels',
      'Flemish',
      'Walloon',
      'European Union',
      'Chocolate',
      'Waffles',
      'Tintin',
      'French',
      'Dutch'
    ],
    'Belize': [
      'Belizean',
      'Belmopan',
      'Caribbean',
      'Central America',
      'Maya',
      'Reef',
      'English',
      'Rainforest',
      'Diverse',
      'Commonwealth'
    ],
    'Benin': [
      'Beninese',
      'Porto-Novo',
      'West Africa',
      'French',
      'Voodoo',
      'Dahomey',
      'Niger River',
      'Savannah',
      'Cotonou',
      'African'
    ],
    'Bermuda': [
      'Bermudian',
      'Hamilton',
      'British Overseas Territory',
      'Atlantic',
      'Pink sand beaches',
      'Triangle',
      'Sailing',
      'Island',
      'Golf',
      'British'
    ],
    'Bhutan': [
      'Bhutanese',
      'Thimphu',
      'Himalayas',
      'Landlocked',
      'Druk Yul',
      'Buddhist',
      'Gross National Happiness',
      'Eastern Himalayas',
      'Monasteries',
      'Dragon Kingdom'
    ],
    'Bolivia': [
      'Bolivian',
      'La Paz',
      'Spanish',
      'Quechua',
      'Aymara',
      'Andes',
      'Landlocked',
      'Altiplano',
      'Coca',
      'Indigenous'
    ],
    'Bosnia and Herzegovina': [
      'Bosnian',
      'Sarajevo',
      'Balkan',
      'Dayton Agreement',
      'European',
      'Bosniak',
      'Serb',
      'Croat',
      'Yugoslavia',
      'War'
    ],
    'Botswana': [
      'Botswanan',
      'Gaborone',
      'Southern Africa',
      'Okavango Delta',
      'Kalahari Desert',
      'Tswana',
      'Diamonds',
      'Stable',
      'Chobe National Park',
      'Landlocked'
    ],
    'Brazil': [
      'Brazilian',
      'Brasília',
      'Portuguese',
      'South America',
      'Amazon Rainforest',
      'Rio de Janeiro',
      'Carnival',
      'Samba',
      'Capoeira',
      'Latin America'
    ],
    'British Indian Ocean Territory': [
      'British Indian Ocean Territory',
      'Diego Garcia',
      'Indian Ocean',
      'Chagos Archipelago',
      'U.S. Military Base',
      'Territorial Dispute',
      'Isolation',
      'Biologically Rich',
      'Strategic Importance',
      'UK Overseas Territory'
    ],
    'British Virgin Islands': [
      'British Virgin Islands',
      'Caribbean',
      'Tortola',
      'Virgin Gorda',
      'English',
      'Island',
      'Tourism',
      'Sailing',
      'Beaches',
      'British'
    ],
    'Brunei': [
      'Bruneian',
      'Bandar Seri Begawan',
      'Borneo',
      'Sultanate',
      'Oil-rich',
      'Malay',
      'Islamic',
      'Southeast Asia',
      'Hassanal Bolkiah',
      'Small'
    ],
    'Bulgaria': [
      'Bulgarian',
      'Sofia',
      'Balkan',
      'European Union',
      'Cyrillic',
      'Rose Valley',
      'Rila Monastery',
      'Black Sea',
      'Thracian',
      'Slavic'
    ],
    'Burkina Faso': [
      'Burkinabé',
      'Ouagadougou',
      'West Africa',
      'Landlocked',
      'Mossi',
      'Sahel',
      'Sankara',
      'French',
      'Savannah',
      'Volta River'
    ],
    'Burundi': [
      'Burundian',
      'Bujumbura',
      'East Africa',
      'Landlocked',
      'Kirundi',
      'Hutu',
      'Tutsi',
      'Lake Tanganyika',
      'French',
      'African'
    ],
    'Cambodia': [
      'Cambodian',
      'Phnom Penh',
      'Khmer',
      'Southeast Asia',
      'Angkor Wat',
      'Mekong River',
      'Buddhist',
      'Kampuchea',
      'French Indochina',
      'Rice'
    ],
    'Cameroon': [
      'Cameroonian',
      'Yaoundé',
      'Douala',
      'Central Africa',
      'Bantu',
      'Francophone',
      'Mount Cameroon',
      'Rainforest',
      'Diverse',
      'Africa'
    ],
    'Canada': [
      'Canadian',
      'Ottawa',
      'Toronto',
      'Montreal',
      'Vancouver',
      'North America',
      'Maple leaf',
      'Hockey',
      'English',
      'French'
    ],
    'Cape Verde': [
      'Cape Verdean',
      'Praia',
      'Cabo Verde',
      'West Africa',
      'Portuguese',
      'Island nation',
      'Creole',
      'Atlantic Ocean',
      'African',
      'Volcanic'
    ],
    'Caribbean Netherlands': [
      'Caribbean Netherlands',
      'Bonaire',
      'Sint Eustatius',
      'Saba',
      'Dutch',
      'Caribbean',
      'Special municipalities',
      'Islands',
      'Netherlands',
      'Caribbean Sea'
    ],
    'Cayman Islands': [
      'Cayman Islands',
      'George Town',
      'Caribbean',
      'British Overseas Territory',
      'Grand Cayman',
      'Coral reefs',
      'Financial hub',
      'Turquoise waters',
      'British',
      'Islands'
    ],
    'Central African Republic': [
      'Central African',
      'Bangui',
      'Central Africa',
      'Landlocked',
      'Sangha River',
      'French',
      'Bantu',
      'Wildlife',
      'Sudanese Savanna',
      'Conflicts'
    ],
    'Chad': [
      'Chadian',
      'N\'Djamena',
      'Central Africa',
      'Landlocked',
      'Lake Chad',
      'Sahel',
      'French',
      'Arab',
      'Sudanese Savanna',
      'Chari River'
    ],
    'Chile': [
      'Chilean',
      'Santiago',
      'Spanish',
      'South America',
      'Andes',
      'Patagonia',
      'Atacama Desert',
      'Mapuche',
      'Wine',
      'Latin America'
    ],
    'China': [
      'Chinese',
      'Beijing',
      'Shanghai',
      'Great Wall',
      'Mandarin',
      'Asia',
      'Han Chinese',
      'Communist',
      'Silk Road',
      'Dragon'
    ],
    'Christmas Islands': [
      'Christmas Island',
      'Indian Ocean',
      'Australian territory',
      'Phosphate mining',
      'Red crab migration',
      'Isolation',
      'Christmas Island National Park',
      'Australia',
      'Asia',
      'Pacific'
    ],
    'Cocos [Keeling] Islands': [
      'Cocos (Keeling) Islands',
      'Indian Ocean',
      'Australian territory',
      'Cocos Malay',
      'Coral atolls',
      'Coconut palms',
      'Isolation',
      'Australia',
      'Asia',
      'Pacific'
    ],
    'Colombia': [
      'Colombian',
      'Bogotá',
      'Spanish',
      'South America',
      'Andes',
      'Coffee',
      'Emeralds',
      'Cocaine',
      'Latin America',
      'Amazon Rainforest'
    ],
    'Comoros': [
      'Comoran',
      'Moroni',
      'Indian Ocean',
      'Comorian',
      'Arabian Sea',
      'French',
      'Volcanic islands',
      'Vanilla',
      'Africa',
      'Swahili'
    ],
    'Democratic Republic Congo': [
      'Democratic Republic of the Congo',
      'Kinshasa',
      'Central Africa',
      'Congo River',
      'Rainforest',
      'Congo Basin',
      'Bantu',
      'Lingala',
      'Great Lakes',
      'Africa'
    ],
    'Republic of Congo': [
      'Republic of the Congo',
      'Brazzaville',
      'Central Africa',
      'Congo River',
      'Rainforest',
      'Bantu',
      'French',
      'Brazzaville',
      'Africa'
    ],
    'Cook Islands': [
      'Cook Islands',
      'Avarua',
      'Polynesia',
      'Pacific',
      'Maori',
      'Island nation',
      'New Zealand',
      'Rarotonga',
      'Tourism',
      'Oceania'
    ],
    'Costa Rica': [
      'Costa Rican',
      'San José',
      'Spanish',
      'Central America',
      'Pura Vida',
      'Rainforests',
      'Biodiversity',
      'Volcanoes',
      'Pacific Ocean',
      'Latin America'
    ],
    'Côte d\'Ivoire': [
      'Ivorian',
      'Yamoussoukro',
      'Abidjan',
      'West Africa',
      'French',
      'Cocoa',
      'African',
      'Ivory Coast',
      'Savannah',
      'Côte d\'Ivoire'
    ],
    'Croatia': [
      'Croatian',
      'Zagreb',
      'Adriatic Sea',
      'European',
      'Dubrovnik',
      'Dalmatian Coast',
      'Plitvice Lakes',
      'European Union',
      'Slavic',
      'Balkan'
    ],
    'Cuba': [
      'Cuban',
      'Havana',
      'Spanish',
      'Caribbean',
      'Communist',
      'Cigar',
      'Sugar',
      'Revolution',
      'Salsa',
      'Island'
    ],
    'Curaçao': [
      'Curaçao',
      'Willemstad',
      'Dutch',
      'Caribbean',
      'Papiamento',
      'Island',
      'Diving',
      'Beaches',
      'Dutch Caribbean',
      'Netherlands'
    ],
    'Cyprus': [
      'Cypriot',
      'Nicosia',
      'Mediterranean',
      'Greek',
      'Turkish',
      'Island nation',
      'Aphrodite',
      'European Union',
      'Cyprus problem',
      'Olive'
    ],
    'Czech Republic': [
      'Czech',
      'Prague',
      'Central Europe',
      'European Union',
      'Bohemia',
      'Slovak',
      'Slavic',
      'Vltava River',
      'Hussite',
      'Castle'
    ],
    'Denmark': [
      'Danish',
      'Copenhagen',
      'Scandinavia',
      'Nordic',
      'Greenland',
      'Faroe Islands',
      'Baltic Sea',
      'Vikings',
      'Hygge',
      'Constitutional monarchy'
    ],
    'Djibouti': [
      'Djiboutian',
      'Djibouti City',
      'East Africa',
      'Horn of Africa',
      'Afar',
      'French',
      'Red Sea',
      'Bab el Mandeb',
      'Ethiopian Highlands',
      'Islam'
    ],
    'Dominica': [
      'Dominican',
      'Roseau',
      'Caribbean',
      'English',
      'Island nation',
      'Rainforest',
      'Sisserou parrot',
      'Nature Island',
      'Commonwealth',
      'Carib'
    ],
    'Dominican Republic': [
      'Dominican',
      'Santo Domingo',
      'Caribbean',
      'Spanish',
      'Hispaniola',
      'Merengue',
      'Baseball',
      'Taino',
      'Cibao Valley',
      'Latin America'
    ],
    'East Timor': [
      'East Timorese',
      'Dili',
      'Southeast Asia',
      'Timor-Leste',
      'Portuguese',
      'Baucau',
      'Pacific',
      'Austronesian',
      'Tetum',
      'Asia'
    ],
    'Ecuador': [
      'Ecuadorian',
      'Quito',
      'Spanish',
      'South America',
      'Galápagos Islands',
      'Andes',
      'Amazon Rainforest',
      'Cotopaxi',
      'Latin America',
      'Pacific'
    ],
    'Egypt': [
      'Egyptian',
      'Cairo',
      'Arabic',
      'North Africa',
      'Nile River',
      'Pyramids',
      'Sphinx',
      'Ancient',
      'Pharaohs',
      'Middle East'
    ],
    'El Salvador': [
      'Salvadoran',
      'San Salvador',
      'Central America',
      'Spanish',
      'Pupusa',
      'Maya',
      'Volcanoes',
      'Pacific Ocean',
      'Coffee',
      'Latin America'
    ],
    'Equatorial Guinea': [
      'Equatorial Guinean',
      'Malabo',
      'Central Africa',
      'Spanish',
      'Bantu',
      'Bioko Island',
      'Oil-rich',
      'Fang',
      'Atlantic Ocean',
      'Africa'
    ],
    'Eritrea': [
      'Eritrean',
      'Asmara',
      'East Africa',
      'Tigrinya',
      'Afar',
      'Red Sea',
      'Ethiopia',
      'Italian',
      'Horn of Africa',
      'Africa'
    ],
    'Estonia': [
      'Estonian',
      'Tallinn',
      'Baltic',
      'Nordic',
      'European Union',
      'Eesti',
      'Singing Revolution',
      'Soviet Republic',
      'Digital society',
      'Baltic Sea'
    ],
    'Eswatini': [
      'Swazi',
      'Mbabane',
      'Southern Africa',
      'Landlocked',
      'Swaziland',
      'Zulu',
      'Kingdom',
      'Reed Dance',
      'Commonwealth',
      'Africa'
    ],
    'Ethiopia': [
      'Ethiopian',
      'Addis Ababa',
      'East Africa',
      'Horn of Africa',
      'Amharic',
      'Abyssinia',
      'Orthodox Christianity',
      'Lucy',
      'Coffee',
      'African'
    ],
    'Falkland Islands [Islas Malvinas]': [
      'Falkland Islands',
      'Stanley',
      'South Atlantic',
      'British Overseas Territory',
      'Malvinas',
      'Penguins',
      'Sheep farming',
      'War',
      'Southern Hemisphere',
      'Islands'
    ],
    'Faroe Islands': [
      'Faroe Islands',
      'Tórshavn',
      'Scandinavia',
      'Nordic',
      'Danish',
      'Atlantic Ocean',
      'Sheep farming',
      'Islands',
      'Autonomous Territory',
      'Baltic Sea'
    ],
    'Fiji': [
      'Fijian',
      'Suva',
      'Melanesia',
      'Pacific',
      'Bula',
      'Island nation',
      'Coral reefs',
      'Kava',
      'Polynesia',
      'Oceania'
    ],
    'Finland': [
      'Finnish',
      'Helsinki',
      'Scandinavia',
      'Nordic',
      'European Union',
      'Sauna',
      'Lakes',
      'Aurora Borealis',
      'Sisu',
      'Baltic Sea'
    ],
    'France': [
      'French',
      'Paris',
      'European Union',
      'Eiffel Tower',
      'Wine',
      'Cheese',
      'Fashion',
      'Revolution',
      'Napoleon',
      'Europe'
    ],
    'French Guiana': [
      'French Guianese',
      'Cayenne',
      'South America',
      'French',
      'Guiana Space Centre',
      'Amazon Rainforest',
      'Kourou',
      'Overseas Department',
      'Latin America',
      'Europe'
    ],
    'French Polynesia': [
      'French Polynesian',
      'Papeete',
      'Polynesia',
      'Pacific',
      'Tahiti',
      'Bora Bora',
      'Islands',
      'French',
      'Nuclear testing',
      'Oceania'
    ],
    'Gabon': [
      'Gabonese',
      'Libreville',
      'Central Africa',
      'French',
      'Equatorial Guinea',
      'Oil-rich',
      'Bantu',
      'Rainforest',
      'Atlantic Ocean',
      'Africa'
    ],
    'Gambia': [
      'Gambian',
      'Banjul',
      'West Africa',
      'English',
      'River Gambia',
      'Smiling Coast',
      'Jollof rice',
      'Africa',
      'Senegal',
      'Commonwealth'
    ],
    'Georgia': [
      'Georgian',
      'Tbilisi',
      'Caucasus',
      'Europe',
      'Eurasia',
      'Sakartvelo',
      'Orthodox Christianity',
      'Mountains',
      'Wine',
      'Former Soviet Republic'
    ],
    'Germany': [
      'German',
      'Berlin',
      'Europe',
      'European Union',
      'Deutschland',
      'Autobahn',
      'Oktoberfest',
      'Beethoven',
      'Angela Merkel',
      'Central Europe'
    ],
    'Ghana': [
      'Ghanaian',
      'Accra',
      'West Africa',
      'English',
      'Ashanti',
      'Gold Coast',
      'Kente',
      'Cocoa',
      'African',
      'Gulf of Guinea'
    ],
    'Gibraltar': [
      'Gibraltarian',
      'Gibraltar',
      'British Overseas Territory',
      'Strait of Gibraltar',
      'Rock of Gibraltar',
      'Mediterranean',
      'Iberian Peninsula',
      'British',
      'Europe',
      'Africa'
    ],
    'Greece': [
      'Greek',
      'Athens',
      'Europe',
      'Mediterranean',
      'Acropolis',
      'Olive',
      'Ancient',
      'Hellenic',
      'Mythology',
      'European Union'
    ],
    'Greenland': [
      'Greenlandic',
      'Nuuk',
      'North America',
      'Arctic',
      'Danish',
      'Inuit',
      'Ice sheet',
      'Polar bears',
      'Island',
      'Autonomous Territory'
    ],
    'Grenada': [
      'Grenadian',
      'St. George\'s',
      'Caribbean',
      'English',
      'Island nation',
      'Spice Isle',
      'Nutmeg',
      'Tourism',
      'Caribbean Sea',
      'Commonwealth'
    ],
    'Guadeloupe': [
      'Guadeloupean',
      'Basse-Terre',
      'Caribbean',
      'French',
      'Creole',
      'Island',
      'Volcanic',
      'Pointe-à-Pitre',
      'France',
      'Caribbean Sea'
    ],
    'Guam': [
      'Guamanian',
      'Hagåtña',
      'Pacific',
      'Micronesia',
      'U.S. Territory',
      'Chamorro',
      'Guam Rail',
      'Island',
      'Tourism',
      'Pacific Ocean'
    ],
    'Guatemala': [
      'Guatemalan',
      'Guatemala City',
      'Central America',
      'Spanish',
      'Maya',
      'Volcanoes',
      'Lake Atitlán',
      'Coffee',
      'Latin America',
      'Mayan'
    ],
    'Guernsey': [
      'Guernsey',
      'St. Peter Port',
      'Channel Islands',
      'English Channel',
      'British Crown Dependency',
      'Island',
      'Cows',
      'Financial center',
      'Europe',
      'English'
    ],
    'Guinea Conakry': [
      'Guinean',
      'Conakry',
      'West Africa',
      'French',
      'Bantu',
      'Nimba Range',
      'Bauxite',
      'Africa',
      'Guinea'
    ],
    'Guinea-Bissau': [
      'Guinea-Bissauan',
      'Bissau',
      'West Africa',
      'Portuguese',
      'Bantu',
      'Cashew nuts',
      'Island nation',
      'Africa',
      'Guinea'
    ],
    'Guyana': [
      'Guyanese',
      'Georgetown',
      'South America',
      'English',
      'Caribbean',
      'Amazon Rainforest',
      'Essequibo River',
      'Rum',
      'Latin America',
      'Commonwealth'
    ],
    'Haiti': [
      'Haitian',
      'Port-au-Prince',
      'Caribbean',
      'French',
      'Creole',
      'Ayiti',
      'Toussaint Louverture',
      'Poverty',
      'Earthquake',
      'Latin America'
    ],
    'Heard and McDonald Islands': [
      'Heard and McDonald Islands',
      'Subantarctic',
      'Australia',
      'Remote',
      'Antarctic',
      'Penguins',
      'No human inhabitants',
      'Southern Ocean',
      'Islands',
      'Australia'
    ],
    'Honduras': [
      'Honduran',
      'Tegucigalpa',
      'Central America',
      'Spanish',
      'Maya',
      'Copán',
      'Bay Islands',
      'Latin America',
      'Cocoa',
      'Caribbean'
    ],
    'Hong Kong': [
      'Hong Kong',
      'Victoria',
      'China',
      'Special Administrative Region',
      'Cantonese',
      'Skyscrapers',
      'Finance',
      'Harbor',
      'Asia',
      'British'
    ],
    'Hungary': [
      'Hungarian',
      'Budapest',
      'Central Europe',
      'European Union',
      'Magyar',
      'Danube River',
      'Paprika',
      'Eastern Bloc',
      'Habsburg',
      'Europe'
    ],
    'Iceland': [
      'Icelandic',
      'Reykjavik',
      'Scandinavia',
      'Nordic',
      'Vikings',
      'Volcanoes',
      'Geysers',
      'Hot springs',
      'Glaciers',
      'Arctic'
    ],
    'India': [
      'Indian',
      'New Delhi',
      'Hindi',
      'South Asia',
      'Bollywood',
      'Taj Mahal',
      'Hindu',
      'Ganges River',
      'Diverse',
      'Asia'
    ],
    'Indonesia': [
      'Indonesian',
      'Jakarta',
      'Bahasa Indonesia',
      'Southeast Asia',
      'Islands',
      'Bali',
      'Java',
      'Sumatra',
      'Diverse',
      'Asia'
    ],
    'Iran': [
      'Iranian',
      'Tehran',
      'Persian',
      'Middle East',
      'Islamic Republic',
      'Cyrus the Great',
      'Shah',
      'Ayatollah',
      'Persepolis',
      'Persia'
    ],
    'Iraq': [
      'Iraqi',
      'Baghdad',
      'Arabic',
      'Middle East',
      'Mesopotamia',
      'Saddam Hussein',
      'Babylon',
      'Tigris River',
      'Euphrates River',
      'Islamic'
    ],
    'Ireland': [
      'Irish',
      'Dublin',
      'Celtic',
      'Europe',
      'Shamrock',
      'Guinness',
      'Leprechaun',
      'Saint Patrick',
      'Cliffs of Moher',
      'Island'
    ],
    'Isle of Mann': [
      'Manx',
      'Douglas',
      'British Crown Dependency',
      'Irish Sea',
      'Norse',
      'Vikings',
      'Celtic',
      'Tynwald',
      'Island',
      'Europe'
    ],
    'Israel': [
      'Israeli',
      'Jerusalem',
      'Hebrew',
      'Middle East',
      'Tel Aviv',
      'Judaism',
      'Dead Sea',
      'Holy Land',
      'Conflict',
      'Mediterranean'
    ],
    'Italy': [
      'Italian',
      'Rome',
      'Vatican City',
      'Europe',
      'Pasta',
      'Renaissance',
      'Colosseum',
      'Venice',
      'Art',
      'Mediterranean'
    ],
    'Jamaica': [
      'Jamaican',
      'Kingston',
      'Caribbean',
      'English',
      'Reggae',
      'Bob Marley',
      'Dunn\'s River Falls',
      'Blue Mountains',
      'Island nation',
      'Commonwealth'
    ],
    'Japan': [
      'Japanese',
      'Tokyo',
      'Asia',
      'Shinto',
      'Samurai',
      'Sushi',
      'Cherry blossoms',
      'Mount Fuji',
      'Anime',
      'Pacific'
    ],
    'Jersey': [
      'Jersey',
      'St. Helier',
      'Channel Islands',
      'English Channel',
      'British Crown Dependency',
      'Island',
      'Financial center',
      'Europe',
      'English'
    ],
    'Jordan': [
      'Jordanian',
      'Amman',
      'Arabic',
      'Middle East',
      'Petra',
      'Dead Sea',
      'Wadi Rum',
      'Hashemite Kingdom',
      'Desert',
      'Islamic'
    ],
    'Kazakhstan': [
      'Kazakh',
      'Nur-Sultan',
      'Central Asia',
      'Russian',
      'Steppe',
      'Caspian Sea',
      'Astana',
      'Eurasia',
      'Soviet Republic',
      'Eurasian'
    ],
    'Kenya': [
      'Kenyan',
      'Nairobi',
      'East Africa',
      'Swahili',
      'Maasai',
      'Safari',
      'Mount Kenya',
      'Great Rift Valley',
      'Wildlife',
      'African'
    ],
    'Kiribati': [
      'I-Kiribati',
      'South Tarawa',
      'Micronesia',
      'Pacific',
      'Island nation',
      'Gilbert Islands',
      'Kiritimati',
      'Oceania',
      'Pacific Ocean'
    ],
    'Kosovo': [
      'Kosovar',
      'Pristina',
      'Balkan',
      'Europe',
      'Albanian',
      'Serbian',
      'Independence',
      'UNESCO',
      'War',
      'Balkans'
    ],
    'Kuwait': [
      'Kuwaiti',
      'Kuwait City',
      'Arabic',
      'Middle East',
      'Oil-rich',
      'Persian Gulf',
      'Islam',
      'Modern',
      'Saud Al-Sabah',
      'Gulf Cooperation Council'
    ],
    'Kyrgyzstan': [
      'Kyrgyz',
      'Bishkek',
      'Central Asia',
      'Russian',
      'Mountainous',
      'Issyk-Kul',
      'Silk Road',
      'Nomadic',
      'Baltic Sea',
      'Eurasian'
    ],
    'Laos': [
      'Laotian',
      'Vientiane',
      'Southeast Asia',
      'Lao',
      'Mekong River',
      'Luang Prabang',
      'Buddhist',
      'French Indochina',
      'Asia',
      'Indochina'
    ],
    'Latvia': [
      'Latvian',
      'Riga',
      'Baltic',
      'European Union',
      'Rūpniecības Revolūcija',
      'Baltic Sea',
      'Art Nouveau',
      'Rundāle Palace',
      'Europe',
      'Northern Europe'
    ],
    'Lebanon': [
      'Lebanese',
      'Beirut',
      'Arabic',
      'Middle East',
      'Cedar',
      'Phoenician',
      'Civil War',
      'Mediterranean',
      'Cedars of God',
      'Levant'
    ],
    'Lesotho': [
      'Lesotho',
      'Maseru',
      'Southern Africa',
      'Landlocked',
      'Basotho',
      'Mountain Kingdom',
      'Drakensberg',
      'South Africa',
      'Sehlabathebe National Park',
      'Africa'
    ],
    'Liberia': [
      'Liberian',
      'Monrovia',
      'West Africa',
      'English',
      'Americo-Liberian',
      'Firestone',
      'Africa',
      'Lone Star',
      'Civil War',
      'Atlantic Ocean'
    ],
    'Libya': [
      'Libyan',
      'Tripoli',
      'Arabic',
      'North Africa',
      'Mediterranean',
      'Gaddafi',
      'Sahara Desert',
      'Berber',
      'Arab',
      'Africa'
    ],
    'Liechtenstein': [
      'Liechtensteiner',
      'Vaduz',
      'Alps',
      'German',
      'Microstate',
      'European Union',
      'Rhine River',
      'Constitutional monarchy',
      'Europe',
      'Germanic'
    ],
    'Lithuania': [
      'Lithuanian',
      'Vilnius',
      'Baltic',
      'European Union',
      'Baltic Sea',
      'Grand Duchy',
      'Basketball',
      'Europe',
      'Northern Europe',
      'Baltics'
    ],
    'Luxembourg': [
      'Luxembourger',
      'Luxembourg City',
      'European Union',
      'Benelux',
      'French',
      'German',
      'Duchy',
      'Financial center',
      'Europe',
      'Western Europe'
    ],
    'Macau': [
      'Macanese',
      'Macao',
      'China',
      'Special Administrative Region',
      'Portuguese',
      'Cotai Strip',
      'Gaming',
      'Asia',
      'Chinese'
    ],
    'Macedonia': [
      'Macedonian',
      'Skopje',
      'Balkan',
      'Europe',
      'Former Yugoslav Republic of Macedonia',
      'Slavic',
      'Alexander the Great',
      'Ohrid',
      'Balkans',
      'Vardar'
    ],
    'Madagascar': [
      'Malagasy',
      'Antananarivo',
      'Indian Ocean',
      'Malagasy language',
      'Lemurs',
      'Vanilla',
      'Baobab trees',
      'Africa',
      'Island nation',
      'African'
    ],
    'Malawi': [
      'Malawian',
      'Lilongwe',
      'Southern Africa',
      'English',
      'Lake Malawi',
      'Nyasaland',
      'African Great Lakes',
      'Africa',
      'Chichewa',
      'Landlocked'
    ],
    'Malaysia': [
      'Malaysian',
      'Kuala Lumpur',
      'Southeast Asia',
      'Malay',
      'Penang',
      'Petronas Towers',
      'Multicultural',
      'Borneo',
      'Islamic',
      'Asia'
    ],
    'Maldives': [
      'Maldivian',
      'Malé',
      'Indian Ocean',
      'Dhivehi',
      'Atolls',
      'Coral reefs',
      'Luxury resorts',
      'Island nation',
      'Asia',
      'South Asia'
    ],
    'Mali': [
      'Malian',
      'Bamako',
      'West Africa',
      'French',
      'Timbuktu',
      'Mansa Musa',
      'Sahel',
      'Niger River',
      'Dogon',
      'African'
    ],
    'Malta': [
      'Maltese',
      'Valletta',
      'Mediterranean',
      'Malta Island',
      'Knight Hospitaller',
      'Megolithic Temples',
      'Euro',
      'Catholic',
      'Europe',
      'Southern Europe'
    ],
    'Marshall Islands': [
      'Marshallese',
      'Majuro',
      'Micronesia',
      'Pacific',
      'Island nation',
      'Nuclear testing',
      'Compact of Free Association',
      'Oceania',
      'Pacific Ocean',
      'Bikini Atoll'
    ],
    'Martinique': [
      'Martinican',
      'Fort-de-France',
      'Caribbean',
      'French',
      'Creole',
      'Island',
      'Volcanic',
      'Mount Pelée',
      'France',
      'Caribbean Sea'
    ],
    'Mauritania': [
      'Mauritanian',
      'Nouakchott',
      'West Africa',
      'Arabic',
      'Berber',
      'Sahara Desert',
      'Moor',
      'Slavery',
      'Islamic Republic',
      'Africa'
    ],
    'Mauritius': [
      'Mauritian',
      'Port Louis',
      'Indian Ocean',
      'English',
      'Creole',
      'Island nation',
      'Aapravasi Ghat',
      'Dodo',
      'Africa',
      'Indian'
    ],
    'Mayotte': [
      'Mahoran',
      'Mamoudzou',
      'Indian Ocean',
      'French',
      'Comoros',
      'Island',
      'Volcanic',
      'France',
      'Comorian',
      'Africa'
    ],
    'Mexico': [
      'Mexican',
      'Mexico City',
      'Spanish',
      'North America',
      'Aztec',
      'Maya',
      'Tequila',
      'Mariachi',
      'Latin America',
      'Cinco de Mayo'
    ],
    'Micronesia': [
      'Micronesian',
      'Palikir',
      'Pacific',
      'Island nation',
      'Federated States of Micronesia',
      'Yap',
      'Pohnpei',
      'Chuuk',
      'Kosrae',
      'Oceania'
    ],
    'Moldova': [
      'Moldovan',
      'Chisinau',
      'Eastern Europe',
      'Romanian',
      'Russian',
      'Transnistria',
      'Wine',
      'Cyrillic',
      'Former Soviet Republic',
      'Europe'
    ],
    'Monaco': [
      'Monegasque',
      'Monaco',
      'French',
      'Italian',
      'Riviera',
      'Casino',
      'Formula 1',
      'Monte Carlo',
      'Microstate',
      'Europe'
    ],
    'Mongolia': [
      'Mongolian',
      'Ulaanbaatar',
      'Central Asia',
      'Mongol Empire',
      'Nomadic',
      'Gobi Desert',
      'Steppe',
      'Yurt',
      'Cyrillic',
      'Eurasia'
    ],
    'Montenegro': [
      'Montenegrin',
      'Podgorica',
      'Balkan',
      'Adriatic Sea',
      'Former Yugoslavia',
      'Cyrillic',
      'Balkans',
      'European',
      'Slavic',
      'Budva'
    ],
    'Montserrat': [
      'Montserratian',
      'Plymouth',
      'Caribbean',
      'English',
      'Island',
      'Volcanic',
      'Soufrière Hills',
      'Caribbean Sea',
      'Montserrat'
    ],
    'Morocco': [
      'Moroccan',
      'Rabat',
      'Arabic',
      'North Africa',
      'Marrakech',
      'Casablanca',
      'Atlas Mountains',
      'Islamic',
      'Maghreb',
      'Africa'
    ],
    'Mozambique': [
      'Mozambican',
      'Maputo',
      'Southern Africa',
      'Portuguese',
      'Mozambique Channel',
      'Bantu',
      'African',
      'Savannah',
      'Indian Ocean',
      'Africa'
    ],
    'Myanmar [Burma]': [
      'Burmese',
      'Naypyidaw',
      'Southeast Asia',
      'Yangon',
      'Buddhist',
      'Mandalay',
      'Shan State',
      'Rohingya',
      'Asia',
      'Burma'
    ],
    'Namibia': [
      'Namibian',
      'Windhoek',
      'Southern Africa',
      'English',
      'German',
      'Namib Desert',
      'Sossusvlei',
      'Herero',
      'Namibian Dollar',
      'Africa'
    ],
    'Nauru': [
      'Nauruan',
      'Yaren',
      'Micronesia',
      'Pacific',
      'Island nation',
      'Phosphate mining',
      'Oceania',
      'Pacific Ocean',
      'Micronesian'
    ],
    'Nepal': [
      'Nepali',
      'Kathmandu',
      'South Asia',
      'Himalayas',
      'Mount Everest',
      'Buddhist',
      'Sherpa',
      'Gurkha',
      'Asia',
      'Sagarmatha'
    ],
    'Netherlands': [
      'Dutch',
      'Amsterdam',
      'European Union',
      'Holland',
      'Windmills',
      'Tulips',
      'Clogs',
      'Canals',
      'Kingdom of the Netherlands',
      'Europe'
    ],
    'New Caledonia': [
      'New Caledonian',
      'Nouméa',
      'Melanesia',
      'Pacific',
      'French',
      'Island',
      'Kanak',
      'Nouvelle-Calédonie',
      'France',
      'Oceania'
    ],
    'New Zealand': [
      'New Zealander',
      'Wellington',
      'Oceania',
      'Pacific',
      'Māori',
      'Aotearoa',
      'Kiwi',
      'Haka',
      'Mount Cook',
      'Islands'
    ],
    'Nicaragua': [
      'Nicaraguan',
      'Managua',
      'Central America',
      'Spanish',
      'Sandinistas',
      'Lake Nicaragua',
      'Volcanoes',
      'Latin America',
      'Contras',
      'Caribbean'
    ],
    'Niger': [
      'Nigerien',
      'Niamey',
      'West Africa',
      'French',
      'Sahel',
      'Sahara Desert',
      'Tuareg',
      'Zinder',
      'African',
      'Landlocked'
    ],
    'Nigeria': [
      'Nigerian',
      'Abuja',
      'West Africa',
      'English',
      'Lagos',
      'Nollywood',
      'Oil-rich',
      'Yoruba',
      'Hausa',
      'Africa'
    ],
    'Niue': [
      'Niuean',
      'Alofi',
      'Polynesia',
      'Pacific',
      'Island nation',
      'Niuean language',
      'Rock of Polynesia',
      'Oceania',
      'Pacific Ocean',
      'New Zealand'
    ],
    'Norfolk Island': [
      'Norfolk Islander',
      'Kingston',
      'Polynesia',
      'Pacific',
      'Island territory',
      'Australian External Territory',
      'Norfuk',
      'Oceania',
      'Pacific Ocean',
      'Australia'
    ],
    'North Korea': [
      'North Korean',
      'Pyongyang',
      'Asia',
      'Korean',
      'Kim Jong-un',
      'Juche',
      'Korean War',
      'Communist',
      'DPRK',
      'Asia'
    ],
    'Northern Mariana Islands': [
      'Northern Mariana Islander',
      'Saipan',
      'Micronesia',
      'Pacific',
      'U.S. Commonwealth',
      'Chamorro',
      'Tinian',
      'Island',
      'Pacific Ocean',
      'Oceania'
    ],
    'Norway': [
      'Norwegian',
      'Oslo',
      'Scandinavia',
      'Nordic',
      'Fjords',
      'Vikings',
      'Northern Lights',
      'Oil-rich',
      'Sami',
      'Baltic Sea'
    ],
    'Oman': [
      'Omani',
      'Muscat',
      'Arabic',
      'Middle East',
      'Sultanate',
      'Desert',
      'Arabian Sea',
      'Islamic',
      'Oil-rich',
      'Gulf'
    ],
    'Pakistan': [
      'Pakistani',
      'Islamabad',
      'South Asia',
      'Urdu',
      'Karachi',
      'Lahore',
      'K2',
      'Indus River',
      'Islamic Republic',
      'Asia'
    ],
    'Palau': [
      'Palauan',
      'Ngerulmud',
      'Micronesia',
      'Pacific',
      'Island nation',
      'Rock Islands',
      'Koror',
      'Oceania',
      'Pacific Ocean',
      'Jellyfish Lake'
    ],
    'Palestinian Territories': [
      'Palestinian',
      'Ramallah',
      'Gaza Strip',
      'West Bank',
      'Arabic',
      'Israeli-Palestinian conflict',
      'Jerusalem',
      'Middle East',
      'Islamic',
      'Holy Land'
    ],
    'Panama': [
      'Panamanian',
      'Panama City',
      'Central America',
      'Spanish',
      'Canal',
      'Bocas del Toro',
      'Latin America',
      'Isthmus',
      'Pacific',
      'Caribbean'
    ],
    'Papua New Guinea': [
      'Papua New Guinean',
      'Port Moresby',
      'Melanesia',
      'Pacific',
      'Island nation',
      'Bougainville',
      'Sepik River',
      'Oceania',
      'Pacific Ocean',
      'Mount Hagen'
    ],
    'Paraguay': [
      'Paraguayan',
      'Asunción',
      'South America',
      'Spanish',
      'Guaraní',
      'Triple Alliance War',
      'Latin America',
      'Landlocked',
      'Yerba mate',
      'Itaipu Dam'
    ],
    'Peru': [
      'Peruvian',
      'Lima',
      'South America',
      'Spanish',
      'Inca',
      'Machu Picchu',
      'Andes',
      'Amazon Rainforest',
      'Latin America',
      'Pacific'
    ],
    'Philippines': [
      'Filipino',
      'Manila',
      'Southeast Asia',
      'Tagalog',
      'Visayas',
      'Mindanao',
      'Archipelago',
      'Rice terraces',
      'Philippine Eagle',
      'Asia'
    ],
    'Poland': [
      'Polish',
      'Warsaw',
      'European Union',
      'Kraków',
      'Pierogi',
      'Solidarity',
      'Vistula River',
      'Eastern Bloc',
      'European',
      'Central Europe'
    ],
    'Portugal': [
      'Portuguese',
      'Lisbon',
      'European Union',
      'Porto',
      'Fado',
      'Port Wine',
      'Discoveries',
      'Algarve',
      'Iberian Peninsula',
      'Southern Europe'
    ],
    'Puerto Rico': [
      'Puerto Rican',
      'San Juan',
      'Caribbean',
      'Spanish',
      'U.S. Territory',
      'Taino',
      'Salsa',
      'Island',
      'Latin America',
      'Commonwealth'
    ],
    'Qatar': [
      'Qatari',
      'Doha',
      'Arabic',
      'Middle East',
      'Gulf',
      'Oil-rich',
      'Islamic',
      'Qatar Airways',
      'Pearl diving',
      'Gulf Cooperation Council'
    ],
    'Réunion': [
      'Réunionese',
      'Saint-Denis',
      'Indian Ocean',
      'French',
      'Creole',
      'Piton de la Fournaise',
      'Island',
      'Volcanic',
      'France',
      'Africa'
    ],
    'Romania': [
      'Romanian',
      'Bucharest',
      'European Union',
      'Transylvania',
      'Dracula',
      'Carpathian Mountains',
      'Eastern Bloc',
      'European',
      'Balkan',
      'Europe'
    ],
    'Russia': [
      'Russian',
      'Moscow',
      'Eurasia',
      'Europe',
      'Asia',
      'Cyrillic',
      'Tsar',
      'Vodka',
      'Trans-Siberian Railway',
      'Former Soviet Union'
    ],
    'Rwanda': [
      'Rwandan',
      'Kigali',
      'East Africa',
      'Kinyarwanda',
      'Genocide',
      'Volcanoes National Park',
      'Land of a Thousand Hills',
      'Africa',
      'Great Lakes',
      'Central Africa'
    ],
    'Saint Barthélemy': [
      'Saint Barthélemois',
      'Gustavia',
      'Caribbean',
      'French',
      'Creole',
      'Island',
      'Luxury',
      'France',
      'Caribbean Sea'
    ],
    'Saint Helena': [
      'Saint Helenian',
      'Jamestown',
      'Atlantic Ocean',
      'English',
      'Island',
      'Napoleon',
      'Remote',
      'South Atlantic',
      'Africa'
    ],
    'St. Kitts': [
      'Kittitian',
      'Basseterre',
      'Caribbean',
      'English',
      'Nevis',
      'Island',
      'Sugar plantations',
      'Caribbean Sea',
      'Commonwealth'
    ],
    'St. Lucia': [
      'Saint Lucian',
      'Castries',
      'Caribbean',
      'English',
      'Pitons',
      'Sulphur Springs',
      'Island',
      'Caribbean Sea',
      'Commonwealth'
    ],
    'Saint Martin': [
      'Saint-Martinoise',
      'Marigot',
      'Caribbean',
      'French',
      'Dutch',
      'Creole',
      'Island',
      'Sint Maarten',
      'France',
      'Caribbean Sea'
    ],
    'Saint Pierre and Miquelon': [
      'Saint-Pierrais',
      'Saint-Pierre',
      'North America',
      'French',
      'Islands',
      'Creole',
      'France',
      'Atlantic Ocean',
      'Island'
    ],
    'St. Vincent': [
      'Saint Vincentian',
      'Kingstown',
      'Caribbean',
      'English',
      'Grenadines',
      'Island',
      'Pirates of the Caribbean',
      'Caribbean Sea',
      'Commonwealth'
    ],
    'Samoa': [
      'Samoan',
      'Apia',
      'Polynesia',
      'Pacific',
      'Island nation',
      'Upolu',
      'Savai\'i',
      'Oceania',
      'Pacific Ocean',
      'Pacific Islanders'
    ],
    'San Marino': [
      'Sammarinese',
      'San Marino',
      'Europe',
      'Italian',
      'Microstate',
      'Mount Titano',
      'Italian Peninsula',
      'Europe',
      'Southern Europe'
    ],
    'São Tomé and Príncipe': [
      'São Toméan',
      'São Tomé',
      'Africa',
      'Portuguese',
      'Island nation',
      'Cocoa',
      'São Tomé Island',
      'Príncipe',
      'Gulf of Guinea'
    ],
    'Saudi Arabia': [
      'Saudi',
      'Riyadh',
      'Arabic',
      'Middle East',
      'Mecca',
      'Medina',
      'Desert',
      'Islamic',
      'Oil-rich',
      'Gulf'
    ],
    'Senegal': [
      'Senegalese',
      'Dakar',
      'West Africa',
      'French',
      'Wolof',
      'Sahel',
      'Goree Island',
      'African',
      'Atlantic Ocean',
      'Africa'
    ],
    'Serbia': [
      'Serbian',
      'Belgrade',
      'Balkan',
      'Europe',
      'Balkans',
      'Cyrillic',
      'Former Yugoslavia',
      'European',
      'Slavic',
      'Balkan Peninsula'
    ],
    'Seychelles': [
      'Seychellois',
      'Victoria',
      'Indian Ocean',
      'English',
      'Creole',
      'Island nation',
      'Aldabra',
      'Coral atolls',
      'Africa'
    ],
    'Sierra Leone': [
      'Sierra Leonean',
      'Freetown',
      'West Africa',
      'English',
      'Krio',
      'Blood Diamonds',
      'African',
      'Atlantic Ocean',
      'Africa'
    ],
    'Singapore': [
      'Singaporean',
      'Singapore',
      'Southeast Asia',
      'Malay',
      'Chinese',
      'Indian',
      'Merlion',
      'Gardens by the Bay',
      'Asia',
      'City-state'
    ],
    'Sint Maarten': [
      'Sint Maartener',
      'Philipsburg',
      'Caribbean',
      'Dutch',
      'Creole',
      'Island',
      'Saint Martin',
      'Kingdom of the Netherlands',
      'Caribbean Sea'
    ],
    'Slovakia': [
      'Slovak',
      'Bratislava',
      'European Union',
      'Central Europe',
      'Tatra Mountains',
      'Former Czechoslovakia',
      'European',
      'Slavic',
      'Europe'
    ],
    'Slovenia': [
      'Slovenian',
      'Ljubljana',
      'European Union',
      'Central Europe',
      'Julian Alps',
      'Yugoslavia',
      'European',
      'Slavic',
      'Europe'
    ],
    'Solomon Islands': [
      'Solomon Islander',
      'Honiara',
      'Melanesia',
      'Pacific',
      'Island nation',
      'Guadalcanal',
      'Coral reefs',
      'Oceania',
      'Pacific Ocean'
    ],
    'Somalia': [
      'Somali',
      'Mogadishu',
      'Horn of Africa',
      'Somali',
      'Arabic',
      'Islamic',
      'Piracy',
      'Horn of Africa',
      'Africa'
    ],
    'South Africa': [
      'South African',
      'Pretoria',
      'Cape Town',
      'Johannesburg',
      'Southern Africa',
      'English',
      'Afrikaans',
      'Zulu',
      'Apartheid',
      'Africa'
    ],
    'South Georgia and the South Sandwich Islands': [
      'South Georgia',
      'South Sandwich Islands',
      'Subantarctic',
      'British Overseas Territory',
      'Penguins',
      'Southern Ocean',
      'Islands',
      'Antarctica',
      'Atlantic Ocean',
      'Isolation'
    ],
    'South Korea': [
      'South Korean',
      'Seoul',
      'Asia',
      'Korean',
      'K-pop',
      'Kimchi',
      'Demilitarized Zone',
      'Technology',
      'Asia'
    ],
    'South Sudan': [
      'South Sudanese',
      'Juba',
      'East Africa',
      'English',
      'Arabic',
      'Nile River',
      'Independence',
      'African',
      'Africa'
    ],
    'Spain': [
      'Spanish',
      'Madrid',
      'European Union',
      'Barcelona',
      'Flamenco',
      'Paella',
      'Siesta',
      'Iberian Peninsula',
      'Europe',
      'Southern Europe'
    ],
    'Sri Lanka': [
      'Sri Lankan',
      'Colombo',
      'South Asia',
      'Sinhala',
      'Tamil',
      'Ceylon',
      'Tea',
      'Buddhist',
      'Indian Ocean',
      'Asia'
    ],
    'Sudan': [
      'Sudanese',
      'Khartoum',
      'North Africa',
      'Arabic',
      'Nubian',
      'Nile River',
      'Islamic',
      'Darfur',
      'Africa'
    ],
    'Suriname': [
      'Surinamese',
      'Paramaribo',
      'South America',
      'Dutch',
      'Creole',
      'Maroons',
      'Diverse',
      'Latin America',
      'Atlantic Ocean'
    ],
    'Svalbard and Jan Mayen': [
      'Svalbard',
      'Longyearbyen',
      'Jan Mayen',
      'Arctic',
      'Norwegian',
      'Polar bears',
      'Islands',
      'Spitsbergen',
      'Isolation',
      'Northern Europe'
    ],
    'Sweden': [
      'Swedish',
      'Stockholm',
      'Scandinavia',
      'Nordic',
      'Vikings',
      'Abba',
      'Fjords',
      'Northern Lights',
      'Baltic Sea',
      'Europe'
    ],
    'Switzerland': [
      'Swiss',
      'Bern',
      'European Union',
      'German',
      'French',
      'Italian',
      'Alps',
      'Chocolate',
      'Watches',
      'Central Europe'
    ],
    'Syria': [
      'Syrian',
      'Damascus',
      'Arabic',
      'Middle East',
      'Civil War',
      'Palmyra',
      'Islamic',
      'Ancient',
      'Levant',
      'Gulf'
    ],
    'Taiwan': [
      'Taiwanese',
      'Taipei',
      'East Asia',
      'Mandarin',
      'Chinese',
      'Taipei 101',
      'Democracy',
      'Asia',
      'Formosa',
      'Pacific'
    ],
    'Tajikistan': [
      'Tajik',
      'Dushanbe',
      'Central Asia',
      'Russian',
      'Tajik Persian',
      'Pamir Mountains',
      'Cyrillic',
      'Soviet Republic',
      'Eurasian',
      'Silk Road'
    ],
    'Tanzania': [
      'Tanzanian',
      'Dodoma',
      'East Africa',
      'Swahili',
      'Zanzibar',
      'Mount Kilimanjaro',
      'Serengeti',
      'African',
      'Great Rift Valley',
      'Africa'
    ],
    'Thailand': [
      'Thai',
      'Bangkok',
      'Southeast Asia',
      'Thai language',
      'Buddhist',
      'Elephants',
      'Pad Thai',
      'Land of Smiles',
      'Asia',
      'Siam'
    ],
    'Togo': [
      'Togolese',
      'Lome',
      'West Africa',
      'French',
      'Ewe',
      'African',
      'Togoland',
      'Gulf of Guinea',
      'Africa'
    ],
    'Tokelau': [
      'Tokelauan',
      'Atafu',
      'Polynesia',
      'Pacific',
      'Island territory',
      'Oceania',
      'Pacific Ocean',
      'New Zealand',
      'Atolls',
      'Isolation'
    ],
    'Tonga': [
      'Tongan',
      'Nuku\'alofa',
      'Polynesia',
      'Pacific',
      'Island nation',
      'Haʻapai',
      'Vavaʻu',
      'Oceania',
      'Pacific Ocean',
      'Friendly Islands'
    ],
    'Trinidad/Tobago': [
      'Trinidadian',
      'Port of Spain',
      'Tobagonian',
      'Caribbean',
      'English',
      'Calypso',
      'Carnival',
      'Island nation',
      'Caribbean Sea',
      'Commonwealth'
    ],
    'Tunisia': [
      'Tunisian',
      'Tunis',
      'Arabic',
      'North Africa',
      'Carthage',
      'Islamic',
      'Mediterranean',
      'Jasmine Revolution',
      'Maghreb',
      'Africa'
    ],
    'Turkey': [
      'Turkish',
      'Ankara',
      'Istanbul',
      'Europe',
      'Asia',
      'Turkish language',
      'Kebab',
      'Hagia Sophia',
      'Bosphorus',
      'Eurasia'
    ],
    'Turkmenistan': [
      'Turkmen',
      'Ashgabat',
      'Central Asia',
      'Turkic',
      'Caspian Sea',
      'Karakum Desert',
      'Cyrillic',
      'Soviet Republic',
      'Eurasian',
      'Silk Road'
    ],
    'Turks and Caicos Islands': [
      'Turks and Caicos Islander',
      'Cockburn Town',
      'Caribbean',
      'English',
      'Island territory',
      'Turks Islands',
      'Caicos Islands',
      'Caribbean Sea',
      'British Overseas Territory'
    ],
    'Tuvalu': [
      'Tuvaluan',
      'Funafuti',
      'Polynesia',
      'Pacific',
      'Island nation',
      'Oceania',
      'Pacific Ocean',
      'Ellice Islands',
      'Isolation',
      'Climate Change'
    ],
    'U.S. Virgin Islands': [
      'Virgin Islander',
      'Charlotte Amalie',
      'Caribbean',
      'English',
      'U.S. Territory',
      'Island territory',
      'Caribbean Sea',
      'United States'
    ],
    'Uganda': [
      'Ugandan',
      'Kampala',
      'East Africa',
      'English',
      'Swahili',
      'Ugandan Shilling',
      'African',
      'Great Rift Valley',
      'Lake Victoria',
      'Africa'
    ],
    'Ukraine': [
      'Ukrainian',
      'Kyiv',
      'Eastern Europe',
      'Kiev',
      'Cyrillic',
      'Chernobyl',
      'Carpathian Mountains',
      'Former Soviet Republic',
      'European',
      'Slavic'
    ],
    'United Arab Emirates': [
      'Emirati',
      'Abu Dhabi',
      'Dubai',
      'Arabic',
      'Middle East',
      'Oil-rich',
      'Islamic',
      'Burj Khalifa',
      'Gulf'
    ],
    'United Kingdom': [
      'British',
      'London',
      'European Union',
      'England',
      'Scotland',
      'Wales',
      'Northern Ireland',
      'Union Jack',
      'Commonwealth',
      'United'
    ],
    'United States': [
      'American',
      'Washington, D.C.',
      'New York',
      'Los Angeles',
      'English',
      'Diverse',
      'Liberty',
      'Stars and Stripes',
      'North America',
      'Pacific'
    ],
    'Uruguay': [
      'Uruguayan',
      'Montevideo',
      'South America',
      'Spanish',
      'Mate',
      'Latin America',
      'Rio de la Plata',
      'Tango',
      'Atlantic Ocean'
    ],
    'Uzbekistan': [
      'Uzbek',
      'Tashkent',
      'Central Asia',
      'Turkic',
      'Cyrillic',
      'Silk Road',
      'Soviet Republic',
      'Eurasian',
      'Samarkand',
      'Bukhara'
    ],
    'Vanuatu': [
      'Vanuatuan',
      'Port Vila',
      'Melanesia',
      'Pacific',
      'Island nation',
      'Oceania',
      'Pacific Ocean',
      'Bislama',
      'Volcanic',
      'Islands'
    ],
    'Vatican City': [
      'Vatican',
      'Vatican City',
      'Europe',
      'Italian',
      'Holy See',
      'St. Peter\'s Basilica',
      'Pope',
      'City-state',
      'Europe'
    ],
    'Venezuela': [
      'Venezuelan',
      'Caracas',
      'South America',
      'Spanish',
      'Andes',
      'Amazon Rainforest',
      'Oil-rich',
      'Latin America',
      'Latin',
      'Orinoco'
    ],
    'Vietnam': [
      'Vietnamese',
      'Hanoi',
      'Southeast Asia',
      'Ho Chi Minh City',
      'Vietnam War',
      'Mekong Delta',
      'Asia',
      'Communist',
      'Indochina'
    ],
    'Wallis and Futuna': [
      'Wallisian',
      'Mata-Utu',
      'Polynesia',
      'Pacific',
      'Island territory',
      'Oceania',
      'Pacific Ocean',
      'French',
      'Isolation'
    ],
    'Western Sahara': [
      'Sahrawi',
      'Laayoune',
      'North Africa',
      'Arabic',
      'Morocco',
      'Polisario Front',
      'African',
      'Sahara Desert',
      'Africa'
    ],
    'Yemen': [
      'Yemeni',
      'Sanaa',
      'Arabic',
      'Middle East',
      'Civil War',
      'Arabian Peninsula',
      'Islamic',
      'Ancient',
      'Gulf'
    ],
    'Zambia': [
      'Zambian',
      'Lusaka',
      'Southern Africa',
      'English',
      'Victoria Falls',
      'Zambezi River',
      'African',
      'Copperbelt',
      'Africa'
    ],
    'Zimbabwe': [
      'Zimbabwean',
      'Harare',
      'Southern Africa',
      'English',
      'Victoria Falls',
      'Great Zimbabwe',
      'African',
      'Copperbelt',
      'Africa'
    ],
  };
}
