
class SelectorHelper {
  static List countryList = [
    'Afghanistan',
    'Åland Islands',
    'Albania',
    'Algeria',
    'American Samoa',
    'Andorra',
    'Angola',
    'Anguilla',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Aruba',
    'Ascension Island',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'British Indian Ocean Territory',
    'British Virgin Islands',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Cape Verde',
    'Caribbean Netherlands',
    'Cayman Islands',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Christmas Island',
    'Cocos [Keeling] Islands',
    'Colombia',
    'Comoros',
    'Democratic Republic of the Congo',
    'Republic of the Congo',
    'Cook Islands',
    'Costa Rica',
    'Côte d\'Ivoire',
    'Croatia',
    'Cuba',
    'Curaçao',
    'Cyprus',
    'Czechia',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'Timor-Leste',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini',
    'Ethiopia',
    'Falkland Islands [Islas Malvinas]',
    'Faroe Islands',
    'Fiji',
    'Finland',
    'France',
    'French Guiana',
    'French Polynesia',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Gibraltar',
    'Greece',
    'Greenland',
    'Grenada',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Heard Island and McDonald Islands',
    'Honduras',
    'Hong Kong',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Isle of Man',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jersey',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Kosovo',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Macau',
    'North Macedonia',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Martinique',
    'Mauritania',
    'Mauritius',
    'Mayotte',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Montserrat',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Caledonia',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Niue',
    'Norfolk Island',
    'North Korea',
    'Northern Mariana Islands',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Palestine',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Puerto Rico',
    'Qatar',
    'Réunion',
    'Romania',
    'Russia',
    'Rwanda',
    'Saint Barthélemy',
    'Saint Helena',
    'Saint Kitts',
    'Saint Lucia',
    'Saint Martin',
    'Saint Pierre and Miquelon',
    'Saint Vincent',
    'Samoa',
    'San Marino',
    'São Tomé and Príncipe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Sint Maarten',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Georgia and the South Sandwich Islands',
    'South Korea',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Svalbard and Jan Mayen',
    'Sweden',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Togo',
    'Tokelau',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Turks and Caicos Islands',
    'Tuvalu',
    'United States Virgin Islands',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Vatican City',
    'Venezuela',
    'Vietnam',
    'Wallis and Futuna',
    'Western Sahara',
    'Yemen',
    'Zambia',
    'Zimbabwe',
  ];

  static List emojiList = [
    '🇦🇫',
    '🇦🇽',
    '🇦🇱',
    '🇩🇿',
    '🇦🇸',
    '🇦🇩',
    '🇦🇴',
    '🇦🇮',
    '🇦🇬',
    '🇦🇷',
    '🇦🇲',
    '🇦🇼',
    '🇦🇨',
    '🇦🇺',
    '🇦🇹',
    '🇦🇿',
    '🇧🇸',
    '🇧🇭',
    '🇧🇩',
    '🇧🇧',
    '🇧🇾',
    '🇧🇪',
    '🇧🇿',
    '🇧🇯',
    '🇧🇲',
    '🇧🇹',
    '🇧🇴',
    '🇧🇦',
    '🇧🇼',
    '🇧🇷',
    '🇮🇴',
    '🇻🇬',
    '🇧🇳',
    '🇧🇬',
    '🇧🇫',
    '🇧🇮',
    '🇰🇭',
    '🇨🇲',
    '🇨🇦',
    '🇨🇻',
    '🇨🇼',
    '🇰🇾',
    '🇨🇫',
    '🇹🇩',
    '🇨🇱',
    '🇨🇳',
    '🇨🇽',
    '🇨🇨',
    '🇨🇴',
    '🇰🇲',
    '🇨🇬',
    '🇨🇩',
    '🇨🇰',
    '🇨🇷',
    '🇨🇮',
    '🇭🇷',
    '🇨🇺',
    '🇨🇼',
    '🇨🇾',
    '🇨🇿',
    '🇩🇰',
    '🇩🇯',
    '🇩🇲',
    '🇩🇴',
    '🇹🇱',
    '🇪🇨',
    '🇪🇬',
    '🇸🇻',
    '🇬🇶',
    '🇪🇷',
    '🇪🇪',
    '🇸🇿',
    '🇪🇹',
    '🇫🇰',
    '🇫🇴',
    '🇫🇯',
    '🇫🇮',
    '🇫🇷',
    '🇬🇫',
    '🇵🇫',
    '🇬🇦',
    '🇬🇲',
    '🇬🇪',
    '🇩🇪',
    '🇬🇭',
    '🇬🇮',
    '🇬🇷',
    '🇬🇱',
    '🇬🇩',
    '🇬🇵',
    '🇬🇺',
    '🇬🇹',
    '🇬🇬',
    '🇬🇼',
    '🇬🇾',
    '🇭🇹',
    '🇦🇺',
    '🇭🇳',
    '🇭🇰',
    '🇭🇺',
    '🇮🇸',
    '🇮🇳',
    '🇮🇩',
    '🇮🇷',
    '🇮🇶',
    '🇮🇪',
    '🇮🇲',
    '🇮🇱',
    '🇮🇹',
    '🇯🇲',
    '🇯🇵',
    '🇯🇪',
    '🇯🇴',
    '🇰🇿',
    '🇰🇪',
    '🇰🇮',
    '🇽🇰',
    '🇰🇼',
    '🇰🇬',
    '🇱🇦',
    '🇱🇻',
    '🇱🇧',
    '🇱🇸',
    '🇱🇷',
    '🇱🇾',
    '🇱🇮',
    '🇱🇹',
    '🇱🇺',
    '🇲🇴',
    '🇲🇰',
    '🇲🇬',
    '🇲🇼',
    '🇲🇾',
    '🇲🇻',
    '🇲🇱',
    '🇲🇹',
    '🇲🇭',
    '🇲🇶',
    '🇲🇷',
    '🇲🇺',
    '🇾🇹',
    '🇲🇽',
    '🇫🇲',
    '🇲🇩',
    '🇲🇨',
    '🇲🇳',
    '🇲🇪',
    '🇲🇸',
    '🇲🇦',
    '🇲🇿',
    '🇲🇲',
    '🇳🇦',
    '🇳🇷',
    '🇳🇵',
    '🇳🇱',
    '🇳🇨',
    '🇳🇿',
    '🇳🇮',
    '🇳🇪',
    '🇳🇬',
    '🇳🇺',
    '🇳🇫',
    '🇰🇵',
    '🇲🇵',
    '🇳🇴',
    '🇴🇲',
    '🇵🇰',
    '🇵🇼',
    '🇵🇸',
    '🇵🇦',
    '🇵🇬',
    '🇵🇾',
    '🇵🇪',
    '🇵🇭',
    '🇵🇱',
    '🇵🇹',
    '🇵🇷',
    '🇶🇦',
    '🇷🇪',
    '🇷🇴',
    '🇷🇺',
    '🇷🇼',
    '🇧🇱',
    '🇸🇭',
    '🇰🇳',
    '🇱🇨',
    '🇲🇫',
    '🇵🇲',
    '🇻🇨',
    '🇼🇸',
    '🇸🇲',
    '🇸🇹',
    '🇸🇦',
    '🇸🇳',
    '🇷🇸',
    '🇸🇨',
    '🇸🇱',
    '🇸🇬',
    '🇸🇽',
    '🇸🇰',
    '🇸🇮',
    '🇸🇧',
    '🇸🇴',
    '🇿🇦',
    '🇬🇸',
    '🇰🇷',
    '🇸🇸',
    '🇪🇸',
    '🇱🇰',
    '🇸🇩',
    '🇸🇷',
    '🇸🇯',
    '🇸🇪',
    '🇨🇭',
    '🇸🇾',
    '🇹🇼',
    '🇹🇯',
    '🇹🇿',
    '🇹🇭',
    '🇹🇬',
    '🇹🇰',
    '🇹🇴',
    '🇹🇹',
    '🇹🇳',
    '🇹🇷',
    '🇹🇲',
    '🇹🇨',
    '🇹🇻',
    '🇻🇮',
    '🇺🇬',
    '🇺🇦',
    '🇦🇪',
    '🇬🇧',
    '🇺🇸',
    '🇺🇾',
    '🇺🇿',
    '🇻🇺',
    '🇻🇦',
    '🇻🇪',
    '🇻🇳',
    '🇼🇫',
    '🇪🇭',
    '🇾🇪',
    '🇿🇲',
    '🇿🇼',
  ];

  static Map<String, String> countryEmojiMap = {
    'Afghanistan': '🇦🇫',
    'Åland Islands': '🇦🇽',
    'Albania': '🇦🇱',
    'Algeria': '🇩🇿',
    'American Samoa': '🇦🇸',
    'Andorra': '🇦🇩',
    'Angola': '🇦🇴',
    'Anguilla': '🇦🇮',
    'Antigua and Barbuda': '🇦🇬',
    'Argentina': '🇦🇷',
    'Armenia': '🇦🇲',
    'Aruba': '🇦🇼',
    'Ascension Island': '🇦🇨',
    'Australia': '🇦🇺',
    'Austria': '🇦🇹',
    'Azerbaijan': '🇦🇿',
    'Bahamas': '🇧🇸',
    'Bahrain': '🇧🇭',
    'Bangladesh': '🇧🇩',
    'Barbados': '🇧🇧',
    'Belarus': '🇧🇾',
    'Belgium': '🇧🇪',
    'Belize': '🇧🇿',
    'Benin': '🇧🇯',
    'Bermuda': '🇧🇲',
    'Bhutan': '🇧🇹',
    'Bolivia': '🇧🇴',
    'Bosnia and Herzegovina': '🇧🇦',
    'Botswana': '🇧🇼',
    'Brazil': '🇧🇷',
    'British Indian Ocean Territory': '🇮🇴',
    'British Virgin Islands': '🇻🇬',
    'Brunei': '🇧🇳',
    'Bulgaria': '🇧🇬',
    'Burkina Faso': '🇧🇫',
    'Burundi': '🇧🇮',
    'Cambodia': '🇰🇭',
    'Cameroon': '🇨🇲',
    'Canada': '🇨🇦',
    'Cape Verde': '🇨🇻',
    'Caribbean Netherlands': '🇨🇼',
    'Cayman Islands': '🇰🇾',
    'Central African Republic': '🇨🇫',
    'Chad': '🇹🇩',
    'Chile': '🇨🇱',
    'China': '🇨🇳',
    'Christmas Island': '🇨🇽',
    'Cocos [Keeling] Islands': '🇨🇨',
    'Colombia': '🇨🇴',
    'Comoros': '🇰🇲',
    'Democratic Republic of the Congo': '🇨🇩',
    'Republic of the Congo': '🇨🇬',
    'Cook Islands': '🇨🇰',
    'Costa Rica': '🇨🇷',
    'Côte d\'Ivoire': '🇨🇮',
    'Croatia': '🇭🇷',
    'Cuba': '🇨🇺',
    'Curaçao': '🇨🇼',
    'Cyprus': '🇨🇾',
    'Czechia': '🇨🇿',
    'Denmark': '🇩🇰',
    'Djibouti': '🇩🇯',
    'Dominica': '🇩🇲',
    'Dominican Republic': '🇩🇴',
    'Timor-Leste': '🇹🇱',
    'Ecuador': '🇪🇨',
    'Egypt': '🇪🇬',
    'El Salvador': '🇸🇻',
    'Equatorial Guinea': '🇬🇶',
    'Eritrea': '🇪🇷',
    'Estonia': '🇪🇪',
    'Eswatini': '🇸🇿',
    'Ethiopia': '🇪🇹',
    'Falkland Islands [Islas Malvinas]': '🇫🇰',
    'Faroe Islands': '🇫🇴',
    'Fiji': '🇫🇯',
    'Finland': '🇫🇮',
    'France': '🇫🇷',
    'French Guiana': '🇬🇫',
    'French Polynesia': '🇵🇫',
    'Gabon': '🇬🇦',
    'Gambia': '🇬🇲',
    'Georgia': '🇬🇪',
    'Germany': '🇩🇪',
    'Ghana': '🇬🇭',
    'Gibraltar': '🇬🇮',
    'Greece': '🇬🇷',
    'Greenland': '🇬🇱',
    'Grenada': '🇬🇩',
    'Guadeloupe': '🇬🇵',
    'Guam': '🇬🇺',
    'Guatemala': '🇬🇹',
    'Guernsey': '🇬🇬',
    'Guinea-Bissau': '🇬🇼',
    'Guyana': '🇬🇾',
    'Haiti': '🇭🇹',
    'Heard Island and McDonald Islands': '🇦🇺',
    'Honduras': '🇭🇳',
    'Hong Kong': '🇭🇰',
    'Hungary': '🇭🇺',
    'Iceland': '🇮🇸',
    'India': '🇮🇳',
    'Indonesia': '🇮🇩',
    'Iran': '🇮🇷',
    'Iraq': '🇮🇶',
    'Ireland': '🇮🇪',
    'Isle of Man': '🇮🇲',
    'Israel': '🇮🇱',
    'Italy': '🇮🇹',
    'Jamaica': '🇯🇲',
    'Japan': '🇯🇵',
    'Jersey': '🇯🇪',
    'Jordan': '🇯🇴',
    'Kazakhstan': '🇰🇿',
    'Kenya': '🇰🇪',
    'Kiribati': '🇰🇮',
    'Kosovo': '🇽🇰',
    'Kuwait': '🇰🇼',
    'Kyrgyzstan': '🇰🇬',
    'Laos': '🇱🇦',
    'Latvia': '🇱🇻',
    'Lebanon': '🇱🇧',
    'Lesotho': '🇱🇸',
    'Liberia': '🇱🇷',
    'Libya': '🇱🇾',
    'Liechtenstein': '🇱🇮',
    'Lithuania': '🇱🇹',
    'Luxembourg': '🇱🇺',
    'Macau': '🇲🇴',
    'North Macedonia': '🇲🇰',
    'Madagascar': '🇲🇬',
    'Malawi': '🇲🇼',
    'Malaysia': '🇲🇾',
    'Maldives': '🇲🇻',
    'Mali': '🇲🇱',
    'Malta': '🇲🇹',
    'Marshall Islands': '🇲🇭',
    'Martinique': '🇲🇶',
    'Mauritania': '🇲🇷',
    'Mauritius': '🇲🇺',
    'Mayotte': '🇾🇹',
    'Mexico': '🇲🇽',
    'Micronesia': '🇫🇲',
    'Moldova': '🇲🇩',
    'Monaco': '🇲🇨',
    'Mongolia': '🇲🇳',
    'Montenegro': '🇲🇪',
    'Montserrat': '🇲🇸',
    'Morocco': '🇲🇦',
    'Mozambique': '🇲🇿',
    'Myanmar': '🇲🇲',
    'Namibia': '🇳🇦',
    'Nauru': '🇳🇷',
    'Nepal': '🇳🇵',
    'Netherlands': '🇳🇱',
    'New Caledonia': '🇳🇨',
    'New Zealand': '🇳🇿',
    'Nicaragua': '🇳🇮',
    'Niger': '🇳🇪',
    'Nigeria': '🇳🇬',
    'Niue': '🇳🇺',
    'Norfolk Island': '🇳🇫',
    'North Korea': '🇰🇵',
    'Northern Mariana Islands': '🇲🇵',
    'Norway': '🇳🇴',
    'Oman': '🇴🇲',
    'Pakistan': '🇵🇰',
    'Palau': '🇵🇼',
    'Palestine': '🇵🇸',
    'Panama': '🇵🇦',
    'Papua New Guinea': '🇵🇬',
    'Paraguay': '🇵🇾',
    'Peru': '🇵🇪',
    'Philippines': '🇵🇭',
    'Poland': '🇵🇱',
    'Portugal': '🇵🇹',
    'Puerto Rico': '🇵🇷',
    'Qatar': '🇶🇦',
    'Réunion': '🇷🇪',
    'Romania': '🇷🇴',
    'Russia': '🇷🇺',
    'Rwanda': '🇷🇼',
    'Saint Barthélemy': '🇧🇱',
    'Saint Helena': '🇸🇭',
    'Saint Kitts': '🇰🇳',
    'Saint Lucia': '🇱🇨',
    'Saint Martin': '🇲🇫',
    'Saint Pierre and Miquelon': '🇵🇲',
    'Saint Vincent': '🇻🇨',
    'Samoa': '🇼🇸',
    'San Marino': '🇸🇲',
    'São Tomé and Príncipe': '🇸🇹',
    'Saudi Arabia': '🇸🇦',
    'Senegal': '🇸🇳',
    'Serbia': '🇷🇸',
    'Seychelles': '🇸🇨',
    'Sierra Leone': '🇸🇱',
    'Singapore': '🇸🇬',
    'Sint Maarten': '🇸🇽',
    'Slovakia': '🇸🇰',
    'Slovenia': '🇸🇮',
    'Solomon Islands': '🇸🇧',
    'Somalia': '🇸🇴',
    'South Africa': '🇿🇦',
    'South Georgia and the South Sandwich Islands': '🇬🇸',
    'South Korea': '🇰🇷',
    'South Sudan': '🇸🇸',
    'Spain': '🇪🇸',
    'Sri Lanka': '🇱🇰',
    'Sudan': '🇸🇩',
    'Suriname': '🇸🇷',
    'Svalbard and Jan Mayen': '🇸🇯',
    'Sweden': '🇸🇪',
    'Switzerland': '🇨🇭',
    'Syria': '🇸🇾',
    'Taiwan': '🇹🇼',
    'Tajikistan': '🇹🇯',
    'Tanzania': '🇹🇿',
    'Thailand': '🇹🇭',
    'Togo': '🇹🇬',
    'Tokelau': '🇹🇰',
    'Tonga': '🇹🇴',
    'Trinidad and Tobago': '🇹🇹',
    'Tunisia': '🇹🇳',
    'Turkey': '🇹🇷',
    'Turkmenistan': '🇹🇲',
    'Turks and Caicos Islands': '🇹🇨',
    'Tuvalu': '🇹🇻',
    'United States Virgin Islands': '🇻🇮',
    'Uganda': '🇺🇬',
    'Ukraine': '🇺🇦',
    'United Arab Emirates': '🇦🇪',
    'United Kingdom': '🇬🇧',
    'United States': '🇺🇸',
    'Uruguay': '🇺🇾',
    'Uzbekistan': '🇺🇿',
    'Vanuatu': '🇻🇺',
    'Vatican City': '🇻🇦',
    'Venezuela': '🇻🇪',
    'Vietnam': '🇻🇳',
    'Wallis and Futuna': '🇼🇫',
    'Western Sahara': '🇪🇭',
    'Yemen': '🇾🇪',
    'Zambia': '🇿🇲',
    'Zimbabwe': '🇿🇼',
  };

  static List langNames = [
    "Afrikaanse",
    "Shqipik",
    "አማርያ",
    "العربية",
    "Հայուհի",
    "Assamese গেস্টবুক",
    "Aymara markanwa .",
    "Azərbaycanca azərbaycan",
    "Bambara .",
    "Euskara",
    "Беларускі",
    "বাঙালি",
    "भोजपुरी के बा।",
    "Bosanski",
    "български",
    "Calalan",
    "Salida",
    "CHIWE",
    "中国（简化）",
    "中國傳統的）",
    "Ghjunnu corsu",
    "Hrvat",
    "Česky",
    "dansk",
    "ޑިވޭހި",
    "डॉगरी ऐ",
    "Nederlanders",
    "English",
    "Esperanto",
    "Eestni-",
    "Eʋegbe .",
    "Pilipino",
    "Suomen",
    "Français",
    "Frysk",
    "Galiciano",
    "Ganda .",
    "საქართველო",
    "Deutsch",
    "Έλληνας",
    "Guarani .",
    "ગુજરાન",
    "Ayisyen kreyòl",
    "Hausa",
    "He Manaʻo Hawaiʻi",
    "עברי",
    "हिंद",
    "Hmoob",
    "Magyari",
    "Íslensk",
    "Iya",
    "iloko .",
    "Orang Indonesia",
    "Gaelach na hÉireann",
    "Italiana",
    "日本人",
    "Jawa",
    "ಕನ್ನಡ",
    "Қазақ қазақ",
    "ខ្មែរ",
    "Kinyarwanda",
    "कोंकणी 1000000000000.",
    "한국어",
    "Krio bin de",
    "Kurdish (Kurmancî)",
    "کوردیش (سۆرانی)",
    "Кыргызча",
    "ລາວ",
    "Latine",
    "Latvietis",
    "Lingala .",
    "Lietuva",
    "Lëtzebuergesch Ënnert",
    "Македонија",
    "मैथिली २.",
    "Malagasy",
    "Orang Melayu",
    "മലയാളം",
    "Maltin",
    "MAOR Reo Maori",
    "मराठी",
    "ꯃꯦꯏꯇꯦꯏꯂꯟ (ꯃꯅꯤꯄꯨꯔꯤ) ꯑꯃꯁꯨꯡ ꯑꯦꯟ.",
    "mizo .",
    "Ийн",
    "မြန်မာ (ဗမာ)",
    "यन्त्र",
    "Leboea Sotho .",
    "norsk",
    "ଓଡିଆ (ଓଡିଆ)",
    "Oroomoo .",
    "پشتو",
    "ایران",
    "Polski",
    "Português",
    "ਪੰਜਾਬ",
    "Quechua .",
    "Români",
    "Русский",
    "Faʻa-Samoa",
    "संस्कृतम् .",
    "Gàidhlig Shòrnach",
    "Српски језик",
    "Sesotho",
    "Shona",
    "سنڌي هن",
    "සිංහල",
    "Sloven",
    "Slovenska",
    "Naag",
    "Española",
    "Sundanes",
    "Kiswalia",
    "svenska",
    "Тоҷикӣ",
    "தமிழாக",
    "Татар",
    "తెలుగు",
    "ประเทศไทย",
    "ቲግሪንያ .",
    "Tsonga .",
    "Türkçe",
    "Türkmen turkmen",
    "twi .",
    "Українська",
    "اردو",
    "ئۇيغۇر",
    "O'zbek tilida",
    "Người Việt Nam",
    "Gymreic",
    "isiXhosa",
    "יידיש",
    "Yoruba",
    "Vala 1 Zulu"
  ];

  static Map<String, String> langMap = {
    "Afrikaanse": "af",
    "Shqipik": "sq",
    "አማርያ": "am",
    "العربية": "ar",
    "Հայուհի": "hy",
    "Assamese গেস্টবুক": "as",
    "Aymara markanwa .": "ay",
    "Azərbaycanca azərbaycan": "az",
    "Bambara .": "bm",
    "Euskara": "eu",
    "Беларускі": "be",
    "বাঙালি": "bn",
    "भोजपुरी के बा।": "bho",
    "Bosanski": "bs",
    "български": "bg",
    "Calalan": "ca",
    "Salida": "ceb",
    "CHIWE": "ny",
    "中国（简化）": "zh",
    "中國傳統的）": "zh-TW",
    "Ghjunnu corsu": "co",
    "Hrvat": "hr",
    "Česky": "cs",
    "dansk": "da",
    "ޑިވޭހި": "dv",
    "डॉगरी ऐ": "doi",
    "Nederlanders": "nl",
    "English": "en",
    "Esperanto": "eo",
    "Eestni-": "et",
    "Eʋegbe .": "ee",
    "Pilipino": "tl",
    "Suomen": "fi",
    "Français": "fr",
    "Frysk": "fy",
    "Galiciano": "gl",
    "Ganda .": "lg",
    "საქართველო": "ka",
    "Deutsch": "de",
    "Έλληνας": "el",
    "Guarani .": "gn",
    "ગુજરાન": "gu",
    "Ayisyen kreyòl": "ht",
    "Hausa": "ha",
    "He Manaʻo Hawaiʻi": "haw",
    "עברי": "iw",
    "हिंद": "hi",
    "Hmoob": "hmn",
    "Magyari": "hu",
    "Íslensk": "is",
    "Iya": "ig",
    "iloko .": "ilo",
    "Orang Indonesia": "id",
    "Gaelach na hÉireann": "ga",
    "Italiana": "it",
    "日本人": "ja",
    "Jawa": "jw",
    "ಕನ್ನಡ": "kn",
    "Қазақ қазақ": "kk",
    "ខ្មែរ": "km",
    "Kinyarwanda": "rw",
    "कोंकणी 1000000000000.": "gom",
    "한국어": "ko",
    "Krio bin de": "kri",
    "Kurdish (Kurmancî)": "ku",
    "کوردیش (سۆرانی)": "ckb",
    "Кыргызча": "ky",
    "ລາວ": "lo",
    "Latine": "la",
    "Latvietis": "lv",
    "Lingala .": "ln",
    "Lietuva": "lt",
    "Lëtzebuergesch Ënnert": "lb",
    "Македонија": "mk",
    "मैथिली २.": "mai",
    "Malagasy": "mg",
    "Orang Melayu": "ms",
    "മലയാളം": "ml",
    "Maltin": "mt",
    "MAOR Reo Maori": "mi",
    "मराठी": "mr",
    "ꯃꯦꯏꯇꯦꯏꯂꯟ (ꯃꯅꯤꯄꯨꯔꯤ) ꯑꯃꯁꯨꯡ ꯑꯦꯟ.": "mni-Mtei",
    "mizo .": "lus",
    "Ийн": "mn",
    "မြန်မာ (ဗမာ)": "my",
    "यन्त्र": "ne",
    "Leboea Sotho .": "nso",
    "norsk": "no",
    "ଓଡିଆ (ଓଡିଆ)": "or",
    "Oroomoo .": "om",
    "پشتو": "ps",
    "ایران": "fa",
    "Polski": "pl",
    "Português": "pt",
    "ਪੰਜਾਬ": "pa",
    "Quechua .": "qu",
    "Români": "ro",
    "Русский": "ru",
    "Faʻa-Samoa": "sm",
    "संस्कृतम् .": "sa",
    "Gàidhlig Shòrnach": "gd",
    "Српски језик": "sr",
    "Sesotho": "st",
    "Shona": "sn",
    "سنڌي هن": "sd",
    "සිංහල": "si",
    "Sloven": "sk",
    "Slovenska": "sl",
    "Naag": "so",
    "Española": "es",
    "Sundanes": "su",
    "Kiswalia": "sw",
    "svenska": "sv",
    "Тоҷикӣ": "tg",
    "தமிழாக": "ta",
    "Татар": "tt",
    "తెలుగు": "te",
    "ประเทศไทย": "th",
    "ቲግሪንያ .": "ti",
    "Tsonga .": "ts",
    "Türkçe": "tr",
    "Türkmen turkmen": "tk",
    "twi .": "ak",
    "Українська": "uk",
    "اردو": "ur",
    "ئۇيغۇر": "ug",
    "O'zbek tilida": "uz",
    "Người Việt Nam": "vi",
    "Gymreic": "cy",
    "isiXhosa": "xh",
    "יידיש": "yi",
    "Yoruba": "yo",
    "Vala 1 Zulu": "zu"
  };
}
